"""Add listen_test_passed field to Progress model

Revision ID: 19883557cc35
Revises: 
Create Date: 2025-08-27 21:47:44.435295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19883557cc35'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('listen_test_passed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.drop_column('listen_test_passed')

    # ### end Alembic commands ###
