"""Add revision and karaoke credits to Progress model

Revision ID: 43c04d0c103e
Revises: e379187237c4
Create Date: 2025-08-29 18:33:07.179758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43c04d0c103e'
down_revision = 'e379187237c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('revision', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('karaoke', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.drop_column('karaoke')
        batch_op.drop_column('revision')

    # ### end Alembic commands ###
