"""Add topic_speaker column to progress table

Revision ID: 98f9fa8ca792
Revises: 43c04d0c103e
Create Date: 2025-08-30 10:49:39.121218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98f9fa8ca792'
down_revision = '43c04d0c103e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topic_speaker', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.drop_column('topic_speaker')

    # ### end Alembic commands ###
