"""Add pronunciation_score column to progress table

Revision ID: a746c0e8c016
Revises: 98f9fa8ca792
Create Date: 2025-08-30 17:56:07.161458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a746c0e8c016'
down_revision = '98f9fa8ca792'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pronunciation_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('pronunciation_score')

    # ### end Alembic commands ###
